#!/usr/bin/env python3

"""
A wrapper around `git commit` that prompts when (perhaps accidentally)
attempting to commit a mixture of staged and unstaged changes.
"""

import optparse
import sys

import gitutils


@gitutils.entrypoint
def main(argv):
    parser = optparse.OptionParser(
        description=__doc__.strip(),
        usage="%prog [OPTIONS] [--] [PATH...]",
        add_help_option=False,
    )
    parser.disable_interspersed_args()

    parser.add_option("-h", "--help", action="help",
                      help="Show this help message and exit.")
    parser.add_option("--verbose", action="store_true",
                      help="Print verbose debugging messages.")
    parser.add_option("-a", "--all", action="store_true",
                      help="Consider all (both staged and unstaged) "
                           "changes.  This can be enabled by default by "
                           "setting the `submit.all` configuration variable "
                           "to `true`.")
    parser.add_option("--dry-run", action="store_true",
                      help=optparse.SUPPRESS_HELP)

    passthrough_options = {
        ("-p", "--patch"): None,
        ("-C", "--reuse-message"): "COMMIT",
        ("-c", "--reedit-message"): "COMMIT",
        ("--fixup",): "COMMIT",
        ("--squash",): "COMMIT",
        ("--reset-author",): None,
        ("--short",): None,
        ("--branch",): None,
        ("--long",): None,
        ("-F", "--file"): "FILE",
        ("--author",): "AUTHOR",
        ("--date",): "DATE",
        ("-m", "--message"): "MESSAGE",
        ("-t", "--template"): "FILE",
        ("--cleanup",): "MODE",
        ("-e", "--edit"): None,
        ("--no-edit",): None,
        ("--amend",): None,
        ("--pathspec-from-file",): "FILE",
        ("-q", "--quiet"): None,
    }

    passthrough_group = optparse.OptionGroup(
        parser,
        "Options passed through to `git commit`",
        "(See `git help commit` for details about these options.)",
    )

    gitutils.add_passthrough_options(passthrough_group, passthrough_options,
                                     dest="commit_options")
    parser.add_option_group(passthrough_group)

    (opts, args) = parser.parse_args(argv[1:])

    gitutils.verbose = opts.verbose
    if opts.verbose:
        opts.commit_options.append("--verbose")

    opts.all = gitutils.get_option(opts, "all", handler=bool, default=False)

    # Options | Types of changes  |
    # --------+----------+--------+
    #   all   | unstaged | staged | Desired behavior
    # --------+----------+--------+--------------------
    #         |          |        | Do nothing
    #    X    |          |        | Do nothing
    # --------+----------+--------+--------------------
    #         |    X     |        | Submit unstaged/all
    #    X    |    X     |        | Submit unstaged/all
    # --------+----------+--------+--------------------
    #         |          |   X    | Submit staged/all
    #    X    |          |   X    | Submit staged/all
    # --------+----------+--------+--------------------
    #         |    X     |   X    | Submit staged
    #    X    |    X     |   X    | Prompt

    status_dict = gitutils.git_status()

    has_staged_changes = False
    has_unstaged_changes = False
    for (_file_path, file_info) in status_dict.items():
        (staged_code, unstaged_code) = file_info["code"]
        if staged_code != " ":
            has_staged_changes = True
        if unstaged_code != " ":
            has_unstaged_changes = True

    if has_staged_changes != has_unstaged_changes:
        opts.all = True
    elif has_staged_changes and has_unstaged_changes:
        if opts.all:
            print("Both staged and unstaged changes detected.")
            response = gitutils.prompt_with_choices(
                "Submit: (S)taged, (a)ll, (q)uit: ",
                (("s", "staged"), ("a", "all"), ("q", "quit")),
                default="s",
            )
            if response is None or response == "q":
                return 1

            opts.all = response == "a"

    if opts.all:
        opts.commit_options.append("--all")

    command = ("git", "commit", *opts.commit_options, "--", *args)
    if opts.dry_run:
        print(command)
        return 0

    return gitutils.run_command(command).returncode


if __name__ == "__main__":
    sys.exit(main(sys.argv))
