#!/usr/bin/env python3

"""Navigates to a parent commit."""

import sys

import git_prev_next
import gitutils


@gitutils.entrypoint(globals())
def main(argv):
    return git_prev_next.main(git_prev_next.Mode.PREV, __doc__, argv)


if __name__ == "__main__":
    sys.exit(main(sys.argv))
