#!/usr/bin/env python3

"""Shows the diff for a single git commit."""

import argparse
import sys

import gitutils


@gitutils.entrypoint
def main(argv):
    ap = argparse.ArgumentParser(description=__doc__.strip(), add_help=False,
                                 allow_abbrev=False)
    ap.add_argument("-h", "--help", action="help",
                    help="Show this help message and exit.")
    ap.add_argument("--verbose", action="store_true",
                    help="Print verbose debugging messages.")
    ap.add_argument("commitish", metavar="COMMIT", nargs="?",
                    default="HEAD",
                    help="The commit-ish to show the diff of.  Defaults to "
                         "`HEAD`.")

    (args, extra_options) = ap.parse_known_args(argv[1:])

    gitutils.verbose = args.verbose
    commit = gitutils.git_commit_hash(args.commitish)

    # We don't call `git diff` with `--` because `git diff` uses `--` to
    # separate commits from file paths, not options from positional
    # arguments.
    return gitutils.run_command(
        ("git", "diff", *extra_options, commit + "~", commit),
        bufsize=1).returncode


if __name__ == "__main__":
    sys.exit(main(sys.argv))
